import Head from 'next/head'

import { Rates } from './components/rates/rates';

export default function Home() {

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1>Mes composants</h1>

      <Rates rating={2.5} />
    </div>
  )
}
