import Head from 'next/head'

export default function Home() {

  return (
    <main className="page home">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="section intro">
        <div className="container">

        <h1 className="section__title">Developpeur web</h1>

<div className="intro__grid">
  <div className="intro__description">
    <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aliquam id purus ut elit commodo tempus. Sed sagittis cursus enim, quis scelerisque tortor elementum at. Morbi et dui felis. Vivamus sollicitudin a nunc sit amet efficitur. Cras vel turpis sit amet orci rutrum feugiat vel in erat. Suspendisse sed pretium lacus.</p>
    <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aliquam id purus ut elit commodo tempus. Sed sagittis cursus enim, quis scelerisque tortor elementum at. Morbi et dui felis. Vivamus sollicitudin a nunc sit amet efficitur. Cras vel turpis sit amet orci rutrum feugiat vel in erat. Suspendisse sed pretium lacus.</p>
    <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aliquam id purus ut elit commodo tempus. Sed sagittis cursus enim, quis scelerisque tortor elementum at. Morbi et dui felis. Vivamus sollicitudin a nunc sit amet efficitur. Cras vel turpis sit amet orci rutrum feugiat vel in erat. Suspendisse sed pretium lacus.</p>
    
    <div className="intro__call-actions">
      <a href="#" className="btn btn-outline">Mes réalisation</a>
      <a href="#" className="btn btn-outline">Mes Compétences</a>
    </div>
  </div>

  <div className="intro__SVG">
  <svg viewBox="0 0 621 346" fill="none" xmlns="http://www.w3.org/2000/svg">
<path d="M55.0461 12C55.0461 5.37259 60.4187 0 67.0461 0H570.564C577.191 0 582.564 5.37258 582.564 12V314.004C582.564 320.632 577.191 326.004 570.564 326.004H67.0461C60.4187 326.004 55.0461 320.632 55.0461 314.004V244.503V163.002V12Z" fill="#121617"/>
<path d="M0.604736 320.165C0.604736 317.404 2.84331 315.165 5.60474 315.165H615.11C617.871 315.165 620.11 317.404 620.11 320.165V331.646C620.11 332.325 619.974 332.996 619.678 333.607C618.984 335.04 617.53 337.782 615.886 339.344C611.82 343.209 602.019 344.205 600.577 344.332C600.453 344.343 600.333 344.347 600.209 344.347C358.789 344.348 255.467 345.178 14.4064 345.181C13.6745 345.181 12.9345 345.023 12.2818 344.692C10.6016 343.84 7.19899 342 5.29796 340.178C3.6781 338.626 2.06234 336.046 1.21407 334.592C0.802652 333.886 0.604736 333.081 0.604736 332.264V320.165Z" fill="#60676B"/>
<path d="M0.604736 320.165C0.604736 317.404 2.84331 315.165 5.60474 315.165H615.11C617.871 315.165 620.11 317.404 620.11 320.165V332.674H0.604736V320.165Z" fill="#1B1F22"/>
<path d="M72.8804 25.8417C72.8804 20.3188 77.3575 15.8416 82.8804 15.8416H554.73C560.253 15.8416 564.73 20.3188 564.73 25.8416V292.653H72.8804V25.8417Z" fill="#202528"/>
<rect x="273.75" y="321.835" width="74.1529" height="5.83639" rx="2.9182" fill="#60676B"/>
<g filter="url(#filter0_d)">
<rect x="95.3958" y="55.2043" width="177.812" height="43.7034" fill="#60676B"/>
<rect x="101.947" y="62.6256" width="46.7927" height="4.12296" fill="#EFEFF0"/>
<rect x="101.947" y="77.4683" width="115.11" height="4.12296" fill="#EFEFF0"/>
<rect x="101.947" y="87.3634" width="115.11" height="4.12296" fill="#EFEFF0"/>
<rect x="101.947" y="70.047" width="4.67927" height="4.12296" fill="#EFEFF0"/>
<rect x="110.369" y="70.047" width="4.67927" height="4.12296" fill="#EFEFF0"/>
<rect x="118.792" y="70.047" width="4.67928" height="4.12296" fill="#EFEFF0"/>
<rect x="127.215" y="70.047" width="4.67928" height="4.12296" fill="#EFEFF0"/>
</g>
<g filter="url(#filter1_d)">
<rect x="95.3958" y="106.575" width="177.812" height="43.7034" fill="#60676B"/>
<rect x="101.947" y="113.996" width="46.7927" height="4.12296" fill="#EFEFF0"/>
<rect x="101.947" y="128.839" width="115.11" height="4.12296" fill="#EFEFF0"/>
<rect x="101.947" y="138.734" width="115.11" height="4.12296" fill="#EFEFF0"/>
<rect x="101.947" y="121.418" width="4.67927" height="4.12296" fill="#EFEFF0"/>
<rect x="110.369" y="121.418" width="4.67927" height="4.12296" fill="#EFEFF0"/>
<rect x="118.792" y="121.418" width="4.67928" height="4.12296" fill="#EFEFF0"/>
<rect x="127.215" y="121.418" width="4.67928" height="4.12296" fill="#EFEFF0"/>
</g>
<g filter="url(#filter2_d)">
<rect x="95.3958" y="157.946" width="177.812" height="45.2368" fill="#60676B"/>
<rect x="101.947" y="165.627" width="46.7927" height="4.26763" fill="#EFEFF0"/>
<rect x="101.947" y="180.991" width="115.11" height="4.26763" fill="#EFEFF0"/>
<rect x="101.947" y="191.233" width="115.11" height="4.26762" fill="#EFEFF0"/>
<rect x="101.947" y="173.309" width="4.67927" height="4.26763" fill="#EFEFF0"/>
<rect x="110.369" y="173.309" width="4.67927" height="4.26763" fill="#EFEFF0"/>
<rect x="118.792" y="173.309" width="4.67928" height="4.26763" fill="#EFEFF0"/>
<rect x="127.215" y="173.309" width="4.67928" height="4.26763" fill="#EFEFF0"/>
</g>
<g filter="url(#filter3_d)">
<rect x="95.3958" y="209.316" width="177.812" height="45.2368" fill="#60676B"/>
<rect x="101.947" y="216.998" width="46.7927" height="4.26763" fill="#EFEFF0"/>
<rect x="101.947" y="232.361" width="115.11" height="4.26763" fill="#EFEFF0"/>
<rect x="101.947" y="242.604" width="115.11" height="4.26762" fill="#EFEFF0"/>
<rect x="101.947" y="224.68" width="4.67927" height="4.26763" fill="#EFEFF0"/>
<rect x="110.369" y="224.68" width="4.67927" height="4.26763" fill="#EFEFF0"/>
<rect x="118.792" y="224.68" width="4.67928" height="4.26763" fill="#EFEFF0"/>
<rect x="127.215" y="224.68" width="4.67928" height="4.26763" fill="#EFEFF0"/>
</g>
<g filter="url(#filter4_d)">
<rect x="281.84" y="55.2043" width="260.676" height="199.349" fill="#60676B"/>
</g>
<path d="M439.627 173.138H397.904L389.335 179.635L380.766 173.138H362.717V177.593C362.717 183.272 367.133 187.898 372.594 187.989C373.102 190.796 374.331 193.332 376.181 195.317C378.916 198.252 382.894 199.871 387.379 199.871H414.966C419.451 199.871 423.428 198.252 426.164 195.313C428.013 193.329 429.242 190.793 429.75 187.986C432.651 187.939 435.257 186.612 437.065 184.527C438.753 182.529 439.654 180.092 439.627 177.593V173.138Z" fill="#EFEFF0"/>
<path d="M381.318 167.197L389.328 172.431L397.41 167.197H439.627V165.712C439.625 164.001 438.958 162.343 437.74 161.017C436.522 159.691 434.826 158.779 432.939 158.435C432.768 152.923 430.223 148.31 425.518 145.068C421.167 142.054 415.353 140.465 408.696 140.465H393.648C379.391 140.465 369.733 147.662 369.405 158.435C367.518 158.779 365.822 159.691 364.604 161.017C363.386 162.343 362.72 164.001 362.717 165.712V167.197H381.318Z" fill="#EFEFF0"/>
<path d="M456.155 125.613H440.566L442.43 118.993L451.749 116.145L449.659 110.761L436.701 114.474L433.673 125.613H402.844V131.554H406.763L407.152 134.524H408.696C416.847 134.524 424.091 136.547 429.621 140.375C432.697 142.481 435.19 145.182 436.91 148.275C437.971 150.193 438.725 152.233 439.153 154.336C442.267 156.039 444.577 158.691 445.649 161.797C446.722 164.903 446.485 168.249 444.982 171.211C445.862 173.248 446.314 175.411 446.315 177.593C446.315 181.741 444.727 185.693 441.843 188.723C440.058 190.611 437.772 192.076 435.19 192.983C434.311 195.21 433 197.283 431.318 199.109C431.071 199.373 430.818 199.631 430.559 199.88H446.315C449.659 199.88 451.122 198.395 451.54 195.61L459.147 131.563H463.035V125.613H456.155Z" fill="#EFEFF0"/>
<defs>
<filter id="filter0_d" x="93.3958" y="55.2043" width="181.812" height="47.7034" filterUnits="userSpaceOnUse" color-interpolation-filters="sRGB">
<feFlood flood-opacity="0" result="BackgroundImageFix"/>
<feColorMatrix in="SourceAlpha" type="matrix" values="0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 127 0"/>
<feOffset dy="2"/>
<feGaussianBlur stdDeviation="1"/>
<feColorMatrix type="matrix" values="0 0 0 0 0.0486979 0 0 0 0 0.0597396 0 0 0 0 0.0625 0 0 0 0.8 0"/>
<feBlend mode="normal" in2="BackgroundImageFix" result="effect1_dropShadow"/>
<feBlend mode="normal" in="SourceGraphic" in2="effect1_dropShadow" result="shape"/>
</filter>
<filter id="filter1_d" x="93.3958" y="106.575" width="181.812" height="47.7034" filterUnits="userSpaceOnUse" color-interpolation-filters="sRGB">
<feFlood flood-opacity="0" result="BackgroundImageFix"/>
<feColorMatrix in="SourceAlpha" type="matrix" values="0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 127 0"/>
<feOffset dy="2"/>
<feGaussianBlur stdDeviation="1"/>
<feColorMatrix type="matrix" values="0 0 0 0 0.0486979 0 0 0 0 0.0597396 0 0 0 0 0.0625 0 0 0 0.8 0"/>
<feBlend mode="normal" in2="BackgroundImageFix" result="effect1_dropShadow"/>
<feBlend mode="normal" in="SourceGraphic" in2="effect1_dropShadow" result="shape"/>
</filter>
<filter id="filter2_d" x="93.3958" y="157.946" width="181.812" height="49.2368" filterUnits="userSpaceOnUse" color-interpolation-filters="sRGB">
<feFlood flood-opacity="0" result="BackgroundImageFix"/>
<feColorMatrix in="SourceAlpha" type="matrix" values="0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 127 0"/>
<feOffset dy="2"/>
<feGaussianBlur stdDeviation="1"/>
<feColorMatrix type="matrix" values="0 0 0 0 0.0486979 0 0 0 0 0.0597396 0 0 0 0 0.0625 0 0 0 0.8 0"/>
<feBlend mode="normal" in2="BackgroundImageFix" result="effect1_dropShadow"/>
<feBlend mode="normal" in="SourceGraphic" in2="effect1_dropShadow" result="shape"/>
</filter>
<filter id="filter3_d" x="93.3958" y="209.316" width="181.812" height="49.2368" filterUnits="userSpaceOnUse" color-interpolation-filters="sRGB">
<feFlood flood-opacity="0" result="BackgroundImageFix"/>
<feColorMatrix in="SourceAlpha" type="matrix" values="0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 127 0"/>
<feOffset dy="2"/>
<feGaussianBlur stdDeviation="1"/>
<feColorMatrix type="matrix" values="0 0 0 0 0.0486979 0 0 0 0 0.0597396 0 0 0 0 0.0625 0 0 0 0.8 0"/>
<feBlend mode="normal" in2="BackgroundImageFix" result="effect1_dropShadow"/>
<feBlend mode="normal" in="SourceGraphic" in2="effect1_dropShadow" result="shape"/>
</filter>
<filter id="filter4_d" x="279.84" y="55.2043" width="264.676" height="203.349" filterUnits="userSpaceOnUse" color-interpolation-filters="sRGB">
<feFlood flood-opacity="0" result="BackgroundImageFix"/>
<feColorMatrix in="SourceAlpha" type="matrix" values="0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 127 0"/>
<feOffset dy="2"/>
<feGaussianBlur stdDeviation="1"/>
<feColorMatrix type="matrix" values="0 0 0 0 0.07 0 0 0 0 0.0805 0 0 0 0 0.0875 0 0 0 1 0"/>
<feBlend mode="normal" in2="BackgroundImageFix" result="effect1_dropShadow"/>
<feBlend mode="normal" in="SourceGraphic" in2="effect1_dropShadow" result="shape"/>
</filter>
</defs>
</svg>

  </div>
</div>


        </div>
      </div>

      <div className="section alternativly">
        <div className="container">
          <h2 className="section__title">Mes compétences</h2>
        </div>
      </div>
    </main>
  )
}
