import Head from 'next/head'

import React from 'react';

import { Rates } from './components/rates/rates';
import { Skill } from './components/Skill/skill';

export default function Home() {
  
  function createSVG() {
    return {
      __html: "<div>Mon icone</div>"
    }
  }

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1>Mes composants</h1>

      <Skill title={"HTML"}>
          <Rates rating={2.3} />
          <div dangerouslySetInnerHTML={createSVG()} />
      </Skill>
    </div>
  )
}
